### ISSUE TITLE
Support of maps needs clarification

### ISSUE THREAD

**Issue by kyegupov** [aykevl/tinygo#115]
The map type support is described as "very rough, unfinished"  and "incomplete" in the documentation.
This is not helpful to developers: what is working and what is not?

Having this clarified would help the users of tinygo and might encourage to submit fixing pull requests and patches.

**Comment by aykevl** [comment]
Yes, good point. This should be clarified.
I've tried to implement a similar hashmap as the one in the main Go compiler (which is implemented in the runtime). But there are many bugs and missing pieces:

* Adding more than 8 entries is not yet supported at runtime. However, it is supported at compile time (for example, in globals). Large compile-time maps are necessary for the "unicode" package, for example.
* Setting the same key twice at compile time actually inserts it twice, which is not what you'd expect in a hashmap.
* The only supported types in keys are strings and simple types (integers/bools/structs). In practice, this covers the vast majority of maps, but some maps have more difficult key types. I'm not sure yet how to support those, whether by using reflection or generating hash/cmp functions like the main Go compiler does.
* The current map type is not balanced in any way. A normal hashmap uses the first few bits of the hash of the key as a fast bucket lookup. This is not implemented, so map operations on larger maps (where supported) will take O(n) time while they should be O(1).

I've probably missed a few things, but as you can see maps aren't quite ready to be used in practice.

Leaving this bug open until this either fixed or added to the docs.

**Comment by kyegupov** [comment]
Did you plan to follow the implementation in mainline Go? Can the code from it be pulled into this project?

**Comment by aykevl** [comment]
I planned to follow a subset of the implementation. The mainline Go implementation is fairly heavy and has lots of stuff in it to make sure average performance and performance jitter is reduced (every operation takes about the same time). This is great for server applications, but to me, code size is much more important. So I wouldn't blindly copy the implementation.
However, maybe there is a way to copy parts of it to avoid too much duplication of effort. Or possibly more interesting: I've copied most of the design (8 entries per bucket, etc.). Much of that hasn't been implemented but that's the design I would want to copy, as it has been proven to work.

Note: if someone needs a stable/fast map implementation with low jitter at the cost of bigger code size, that may be added as an option just like you can switch the garbage collector. But I don't really see the use of that at the moment.

**Comment by aykevl** [comment]
Status of map support has been added to the docs:
https://tinygo.org/lang-support/#maps
