### ISSUE TITLE
memset in runtime_tinygoarm.go returns void

### ISSUE THREAD

**Issue by kyegupov** [aykevl/tinygo#123]
See https://github.com/aykevl/tinygo/blob/master/src/runtime/runtime_tinygoarm.go#L51

As far as I know, the classic ABI for memset is to return the original starting pointer.

My code (compiled to wasm) complained about a missing memset implementation. When I decided to copy this one, it led to generation of a broken wasm file.

**Comment by aykevl** [comment]
I believe this one is fixed by #137 so I'm going to close this bug. Please let me know if this is still an issue.
