### ISSUE TITLE
Downcasting an interface to an empty struct confuses the compiler

### ISSUE THREAD

**Issue by kyegupov** [aykevl/tinygo#132]
Code:
```
package main

import "fmt"

type empty struct{}
type iface interface {
	Yo()
}

func (e empty) Yo() {
}

func main() {
	var s iface = empty{}
	_, ok := s.(empty)
	fmt.Println(ok)
}
```

Result:

```
tinygo build -o es.wasm es.go
es.go:15:13: undefined local var (from cgo?)
```

**Comment by aykevl** [comment]
This was a simple typo bug, now fixed in c840757352e9f4d41c0207bf8511380b24e8e998. Not sure how it led to that error message but now it's gone.
Note: the fmt package is not yet supported and apparently is even more broken than it was before. Now it throws a verification error.
