### ISSUE TITLE
strings.IndexByte not yet implemented

### ISSUE THREAD

**Issue by deadprogram** [aykevl/tinygo#154]
When trying to call `strings.Contains()` I get the following message:

```shell
/tmp/tinygo124212217/main.o: In function `strings.Index':
../../../../../../../gos/go1.11/src/strings/strings.go:995: undefined reference to `strings.IndexByte'
```

Does this mean that the `strings.IndexByte()` function is not yet implemented in TinyGo? If so, then where exactly should it be added?

**Comment by aykevl** [comment]
The source says this:

```go
// IndexByte returns the index of the first instance of c in s, or -1 if c is not present in s.
func IndexByte(s string, c byte) int // in internal/bytealg
```

So it looks like it is implemented in the runtime, probably with hand-optimized assembly.
You can implement it in TinyGo in src/runtime/strings.go this way:

```go
//go:linkname indexByte strings.IndexByte
func indexByte(...) { ...}
```

For an initial implementation I would avoid optimizing it, just using the most obvious/naive implementation.
