### ISSUE TITLE
stm32: missing files/directory?

### ISSUE THREAD

**Issue by deadprogram** [aykevl/tinygo#17]
I think perhaps the recent commit to add initial stm32 support might be missing some files from the check-in:

```
$ make gen-device-stm32
./tools/gen-device-svd.py lib/cmsis-svd/data/STMicro/ src/device/stm32/ --source=https://github.com/posborne/cmsis-svd/tree/master/data/STMicro
go fmt ./src/device/stm32
can't load package: package github.com/aykevl/tinygo/src/device/stm32: no Go files in /home/ron/.gvm/pkgsets/go1.11/global/src/github.com/aykevl/tinygo/src/device/stm32
Makefile:70: recipe for target 'gen-device-stm32' failed
make: *** [gen-device-stm32] Error 1
```

I do not see a directory named `stm32` in the repo: https://github.com/aykevl/tinygo/tree/master/src/device

**Comment by aykevl** [comment]
You probably need to run:

    git submodule update --init

I have pushed a change that should show a more helpful error message in this case.

**Comment by deadprogram** [comment]
Yes, that was it, thanks. I have an `stm32f030` board I want to try out... Now closing.
