### ISSUE TITLE
LLVM-C/Analysis.h file not found

### ISSUE THREAD

**Issue by OrlanRepo** [aykevl/tinygo#2]
When doing `go get -u github.com/aykevl/tinygo` I'm getting 

```# github.com/aykevl/llvm/bindings/go/llvm
go/src/github.com/aykevl/llvm/bindings/go/llvm/analysis.go:17:10: fatal error: 'llvm-c/Analysis.h' file not found
#include "llvm-c/Analysis.h" // If you are getting an error here read bindings/go/README.txt
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

After doing exactly as in the `bindings/go/README.txt` from `github.com/aykevl/llvm/bindings/go/llvm`. The build of `llvm-go` was a success but TinyGo is still receiving the error show above.

**Comment by OrlanRepo** [comment]
Ok I saw that I have been building the original llvm.org package not aykevl but still I get 
```
# github.com/aykevl/llvm/bindings/go/llvm
go/src/github.com/aykevl/llvm/bindings/go/llvm/dibuilder.go:301: cannot use C.uint(t.Encoding) (type C.uint) as type C.LLVMDWARFTypeEncoding in argument to func literal
```

**Comment by OrlanRepo** [comment]
@aykevl `go version`:
``` go version go1.9.1 darwin/amd64 ```

OS:
`macOS High Sierra V 10.13.6`

**Comment by aykevl** [comment]
I'm afraid this is a bug in LLVM on macOS, not in TinyGo. I'll try again soon with Go 1.9 but as I don't have a macOS machine I can't really reproduce this.

You could try again with Go 1.10, that's what I use for development.

**Comment by aykevl** [comment]
I've been able to reproduce the error in Go 1.9, so the error will most likely go away with Go 1.10.

I've also updated the README with build instructions: https://github.com/aykevl/tinygo#building

**Comment by OrlanRepo** [comment]
Yeah it seems like it will run now. I still got some more problems with LLVM on my machine though. Thanks for a quick response.
