### ISSUE TITLE
AVR: UART not working with latest master

### ISSUE THREAD

**Issue by deadprogram** [aykevl/tinygo#21]
I tried the latest `master`  branch this morning, and seems like the UART is no longer functioning as expected. No data is received by the serial port from the connected host computer when running the `serial` example on AVR. It does work as expected on pca10040.

**Comment by aykevl** [comment]
You probably need to run `make gen-device-avr`. There are updates to the generator script that are not backwards-compatible.

**Comment by deadprogram** [comment]
I already had done both the submodule update and also re-ran that script, as that was needed in order to even compile.

**Comment by aykevl** [comment]
Weird. It's working just fine for me.
Can you maybe send me the compiled .elf file (`make build/serial.elf`)?

**Comment by deadprogram** [comment]
Sure, here you go.
[serial.elf.zip](https://github.com/aykevl/tinygo/files/2410503/serial.elf.zip)

**Comment by deadprogram** [comment]
Wait wrong build command on my previous upload.
[serial.elf.zip](https://github.com/aykevl/tinygo/files/2410506/serial.elf.zip)
 Use this one.

**Comment by aykevl** [comment]
That's a completely empty reset vector. All entries go to the default handler.

... oops, after I run `make gen-device-avr`, I get the same behavior. Will need to investigate this. I know I've been struggling with this issue before but thought it was fixed.

**Comment by aykevl** [comment]
Should be fixed now with ddd4a39cb85a5e652e82edf0d0475f0b5218235b. You'll need to re-run `make gen-device-avr` after updating.

**Comment by deadprogram** [comment]
Thank you, that fixed it. Now closing.
