### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by aykevl** [aykevl/tinygo#47]
Currently, TinyGo doesn't appear to work on OS X with LLVM 7 from homebrew.

  * Support OS X
  * Optional: build on OS X in Travis

**Comment by aykevl** [comment]
See https://github.com/aykevl/go-llvm/pull/1

**Comment by aykevl** [comment]
I think tinygo works now on OS X after installing LLVM with homebrew - but it doesn't support WebAssembly there yet.

**Comment by deadprogram** [comment]
Can this issue now be closed? Anyone able to confirm using Mojave? I am running High Sierra on my test Mac at present.

**Comment by deadprogram** [comment]
Oh, seems like the WASM support is not in there yet?

**Comment by aykevl** [comment]
That's right, homebrew does not include WebAssembly by default (they think it's unstable, see https://github.com/Homebrew/homebrew-core/pull/29068). Also, I assume they haven't enabled the AVR backend either. I don't know much about OS X or homebrew so you should probably look elsewhere for enabling these backends.

But based on your comment it seems to be basically working? In that case I'm closing the issue.
