### ISSUE TITLE
Support MCU development with Docker

### ISSUE THREAD

**Issue by aykevl** [aykevl/tinygo#50]
Currently, the generated Docker image misses a few things important for microcontroller development:

  * autogenerated register descriptors (`make gen-device`)
  * build tools, like binutils, gcc, etc.

Preferably, ARM targets should move to Clang first so we don't depend on GCC, avoiding the extra dependency.

**Comment by deadprogram** [comment]
Probably would be good to have a multi-stage build so the MCU docker and the WASM docker files do not have to bring down all of the unique dependencies of the other.

Also, we would probably need to run the MCU docker with the `--device` flag so we can flash devices, whereas that is not needed for other use cases.

**Comment by deadprogram** [comment]
Just submitted PR https://github.com/aykevl/tinygo/pull/72 to address this issue.

Note that this PR does not attempt to install tools for flashing. Instead, you would use the image for compiling, and then flash the resulting ELF file from your native OS.

**Comment by aykevl** [comment]
Fixed with #72.
